// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOqa-id3cpVBSyAQFTLseAWCsZUQkmYGM',
    appId: '1:76830169839:web:54d9aed46476145097d91a',
    messagingSenderId: '76830169839',
    projectId: 'totalx-b180f',
    authDomain: 'totalx-b180f.firebaseapp.com',
    storageBucket: 'totalx-b180f.appspot.com',
    measurementId: 'G-DCDYET4H19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn4ZajBozx5r6Dd1hCYoTZUO9xjxcSQTU',
    appId: '1:76830169839:android:efc2cddf791cf6bb97d91a',
    messagingSenderId: '76830169839',
    projectId: 'totalx-b180f',
    storageBucket: 'totalx-b180f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANB6o3aYL4QC9XHClh1NWvKXMhcfsRxkc',
    appId: '1:76830169839:ios:bf0c3ecbb6adbd8097d91a',
    messagingSenderId: '76830169839',
    projectId: 'totalx-b180f',
    storageBucket: 'totalx-b180f.appspot.com',
    iosBundleId: 'com.example.totalx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANB6o3aYL4QC9XHClh1NWvKXMhcfsRxkc',
    appId: '1:76830169839:ios:bf0c3ecbb6adbd8097d91a',
    messagingSenderId: '76830169839',
    projectId: 'totalx-b180f',
    storageBucket: 'totalx-b180f.appspot.com',
    iosBundleId: 'com.example.totalx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOqa-id3cpVBSyAQFTLseAWCsZUQkmYGM',
    appId: '1:76830169839:web:390dc2308871da2797d91a',
    messagingSenderId: '76830169839',
    projectId: 'totalx-b180f',
    authDomain: 'totalx-b180f.firebaseapp.com',
    storageBucket: 'totalx-b180f.appspot.com',
    measurementId: 'G-C939F0NCGN',
  );
}
